import Head from 'next/head';
import React from 'react';
import { useRouter } from 'next/router';

import Navbar from '../components/Navbar/Navbar';
import Form from '../components/Form/Form';
import Footer from '../components/Footer/Footer';

const Checkout = () => {
  const router = useRouter();
  return (
    <main className="bg-off-white">
      <Head>
        <title>Checkout | Audiophile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar variant="black" />
      <div className="w-full px-6 mb-20 font-Manrope">
        <section className="w-full min-h-[65px] flex items-center">
          <button onClick={() => router.back()}>
            <p className="text-base font-medium text-black capitalize opacity-50">
              go back
            </p>
          </button>
        </section>
        <Form />
      </div>
      <Footer hasFooterAddition={false} />
    </main>
  );
};

export default Checkout;
