import Head from 'next/head';
import React from 'react';
import { useRouter } from 'next/router';

import Navbar from '../components/Navbar/Navbar';

const Checkout = () => {
  const router = useRouter();
  return (
    <main>
      <Head>
        <title>Checkout | Audiophile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar variant="black" />
      <div className="w-full px-6 font-Manrope">
        <section className="w-full min-h-[65px] flex items-center">
          <button onClick={() => router.back()}>
            <p className="text-base font-medium text-black capitalize opacity-50">
              go back
            </p>
          </button>
        </section>
        <div className="w-full px-6">
          <h2 className="text-3xl font-bold tracking-wider uppercase">
            checkout
          </h2>
        </div>
      </div>
    </main>
  );
};

export default Checkout;
